### ISSUE TITLE
About dbfin website

### ISSUE THREAD

**Issue by jerry622260** [dbfin/bashrc_my#3]
Hello Vadim, It seems that this is the only way I can contact you. I am a PhD student. Recently, I am studying topology munkres. Your website dbfin.com helps me a lot, and I really appreciate it. But, I don't know why I cannot log into your website now. I am waiting for your website to open again. Looking forward to hearing from you.

**Comment by dbfin** [comment]
Should be fixed now. Did not extend it automatically. 

Thanks for your words and for paying my attention to the problem! And good luck with your graduate studies!

**Comment by sleepingsphinx** [comment]
Hello Vadim, I am a sophomore. Recently, I am studying Mathematical Logic. Your website dbfin.com helps me a lot, and I really appreciate it. But, I don't know why I cannot log into your website now. I am waiting for your website to open again. Looking forward to hearing from you !
